project_id = "xazlcbykmummjteoojvf"

[functions.geocode-address]
verify_jwt = false

[functions.enviar-tce]
verify_jwt = true

[functions.validar-dados-tce]
verify_jwt = true

[functions.exportar-dados]
verify_jwt = true

[functions.importar-esfinge]
verify_jwt = false

[functions.enviar-situacao-obras-mensal]
verify_jwt = false

[functions.register-new-tenant]
verify_jwt = false
